### ISSUE TITLE
Allow ECMAScript 6 in jshint-config

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor-boilerplate#13]
Since part of CKEditor projects [start to use  ECMAScript 6](https://github.com/ckeditor/ckeditor5-design/issues/63#issuecomment-120441029) it should be allowed in the `jshint-config`.

**Comment by pjasiun** [comment]
https://github.com/ckeditor/ckeditor-boilerplate/pull/14

**Comment by Reinmar** [comment]
Fixed by 0c1814339.

I also mentioned this preset in the README file: 0fa674a4029

And reported a followup: #16.

**Comment by Reinmar** [comment]
PS. Make sure to read https://github.com/ckeditor/ckeditor-boilerplate/pull/14#issuecomment-128700044 before complaining that it does not work.
