### ISSUE TITLE
Move JSCS and JSHint configs to the main directory

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor-boilerplate#17]
The reason why we need to do so is that:

1. This is the recommended and standard way, so many tools look for these configs there.
2. When having a project in SublimeText which consists of many repositories (CKE5 case) you can only configure ST to use one config file. You cannot specify that in this directory there's file X and in that there's file Y. Since configurations differ, this is a mess. The only solution is to use the standard paths. Then ST3 can easily find configs by itself.

**Comment by pjasiun** [comment]
:+1: We should not try to reinvent everything (we have enough features to reinvent ;) )
